services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: retrieval-demo-qdrant
    ports:
      - "6333:6333"  # HTTP API and Web UI
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local